"""Add settings models

Revision ID: 55b9ff315408
Revises: f5d69b33b59b
Create Date: 2026-02-28 22:53:34.335862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b9ff315408'
down_revision: Union[str, Sequence[str], None] = 'f5d69b33b59b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklist_users_branch_id'), 'blacklist_users', ['branch_id'], unique=False)
    op.create_index(op.f('ix_blacklist_users_id'), 'blacklist_users', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('profiles', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_branch_id'), 'employees', ['branch_id'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.add_column('branches', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('branches', sa.Column('specialization', sa.String(), nullable=True))
    op.add_column('branches', sa.Column('request_frequency_days', sa.Integer(), nullable=True))
    op.add_column('branches', sa.Column('complaint_emails', sa.JSON(), nullable=True))
    op.add_column('branches', sa.Column('reminder_emails', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'reminder_emails')
    op.drop_column('branches', 'complaint_emails')
    op.drop_column('branches', 'request_frequency_days')
    op.drop_column('branches', 'specialization')
    op.drop_column('branches', 'timezone')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_branch_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_blacklist_users_id'), table_name='blacklist_users')
    op.drop_index(op.f('ix_blacklist_users_branch_id'), table_name='blacklist_users')
    op.drop_table('blacklist_users')
    # ### end Alembic commands ###
