"""add indexes and constraints

Revision ID: f5d69b33b59b
Revises: 0002_rating_int_2_5
Create Date: 2026-02-24 09:29:18.797487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d69b33b59b'
down_revision: Union[str, Sequence[str], None] = '0002_rating_int_2_5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_complaints_created_at'), 'complaints', ['created_at'], unique=False)
    op.create_index(op.f('ix_complaints_resolved'), 'complaints', ['resolved'], unique=False)
    op.create_index(op.f('ix_requests_sent_at'), 'requests', ['sent_at'], unique=False)
    op.create_index(op.f('ix_requests_status'), 'requests', ['status'], unique=False)
    op.create_unique_constraint(None, 'requests', ['request_link'])
    op.create_index(op.f('ix_reviews_platform'), 'reviews', ['platform'], unique=False)
    op.create_index(op.f('ix_reviews_published_at'), 'reviews', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_published_at'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_platform'), table_name='reviews')
    op.drop_constraint(None, 'requests', type_='unique')
    op.drop_index(op.f('ix_requests_status'), table_name='requests')
    op.drop_index(op.f('ix_requests_sent_at'), table_name='requests')
    op.drop_index(op.f('ix_complaints_resolved'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_created_at'), table_name='complaints')
    # ### end Alembic commands ###
